server:
  port: ${SERVER_PORT:8765}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:k8s}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-api-gateway-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

zuul:
  sensitiveHeaders:
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000
  prefix: /api
  routes:
    billing:
      path: /billing/**
      url: http://bookstore-billing-service:5001
    catalog:
      path: /catalog/**
      url: http://bookstore-catalog-service:6001
    account:
      path: /account/**
      url: http://bookstore-account-service:4001
    order:
      path: /order/**
      url: http://bookstore-order-service:7001
    payment:
      path: /payment/**
      url: http://bookstore-payment-service:8001
  ribbon:
    eager-load:
      enabled: true
  ribbon-isolation-strategy: THREAD

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000
  eureka:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
